use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

#[derive(Debug, Parser)]
#[command(
    name = "weevil",
    about = "Command-line toolkit for scraping NFO metadata",
    arg_required_else_help = true
)]
pub(crate) struct Cli {
    #[command(subcommand)]
    pub(crate) command: Command,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
#[clap(rename_all = "kebab-case")]
pub(crate) enum FolderMultiStrategy {
    HardLink,
    SoftLink,
    First,
}

#[derive(Debug, Subcommand)]
pub(crate) enum Command {
    #[command(
        name = "name",
        about = "Generate NFO output by name with a Lua script.",
        after_help = "Notes:\n  The Lua run function must return either:\n    - a table matching the NFO movie schema, or\n    - a string containing raw NFO XML."
    )]
    Name {
        #[arg(long, short = 'n', value_name = "NAME")]
        name: String,
        #[arg(long, short = 's', value_name = "SCRIPT")]
        script: PathBuf,
        #[arg(long, short = 'o', value_name = "OUTPUT")]
        output: PathBuf,
    },
    #[command(
        name = "file",
        about = "Generate NFO output from a file, then rename and move assets."
    )]
    File {
        #[arg(long, short = 'i', value_name = "FILE")]
        input: PathBuf,
        #[arg(long, short = 's', value_name = "SCRIPT")]
        script: PathBuf,
        #[arg(
            long,
            short = 'o',
            value_name = "OUTPUT",
            help = "Output path template (without extension)."
        )]
        output: String,
        #[arg(
            long,
            value_name = "REMOVE",
            value_delimiter = ',',
            help = "Comma-separated tokens to remove from the input filename before passing to Lua."
        )]
        input_name_remove: Vec<String>,
        #[arg(
            long,
            value_enum,
            value_name = "MODE",
            default_value = "first",
            help = "How to handle multiple output paths generated by the template."
        )]
        folder_multi: FolderMultiStrategy,
    },
    #[command(
        name = "dir",
        about = "Generate NFO output for each video file in a directory."
    )]
    Dir {
        #[arg(long, short = 'i', value_name = "DIR")]
        input: PathBuf,
        #[arg(long, short = 's', value_name = "SCRIPT")]
        script: PathBuf,
        #[arg(
            long,
            short = 'o',
            value_name = "OUTPUT",
            help = "Output path template (without extension)."
        )]
        output: String,
        #[arg(
            long,
            value_name = "REMOVE",
            value_delimiter = ',',
            help = "Comma-separated tokens to remove from the input filename before passing to Lua."
        )]
        input_name_remove: Vec<String>,
        #[arg(
            long,
            value_enum,
            value_name = "MODE",
            default_value = "first",
            help = "How to handle multiple output paths generated by the template."
        )]
        folder_multi: FolderMultiStrategy,
        #[arg(
            long,
            value_name = "DEPTH",
            default_value = "-1",
            allow_negative_numbers = true,
            help = "Maximum traversal depth; -1 means unlimited."
        )]
        max_depth: i32,
    },
    #[command(
        name = "watch",
        about = "Watch a directory continuously and process newly completed video files."
    )]
    Watch {
        #[arg(long, short = 'i', value_name = "DIR")]
        input: PathBuf,
        #[arg(long, short = 's', value_name = "SCRIPT")]
        script: PathBuf,
        #[arg(
            long,
            short = 'o',
            value_name = "OUTPUT",
            help = "Output path template (without extension)."
        )]
        output: String,
        #[arg(
            long,
            value_name = "REMOVE",
            value_delimiter = ',',
            help = "Comma-separated tokens to remove from the input filename before passing to Lua."
        )]
        input_name_remove: Vec<String>,
        #[arg(
            long,
            value_enum,
            value_name = "MODE",
            default_value = "first",
            help = "How to handle multiple output paths generated by the template."
        )]
        folder_multi: FolderMultiStrategy,
        #[arg(
            long,
            value_name = "DEPTH",
            default_value = "-1",
            allow_negative_numbers = true,
            help = "Maximum traversal depth; -1 means unlimited."
        )]
        max_depth: i32,
    },
}

#[cfg(test)]
#[path = "tests/cli.rs"]
mod tests;
