use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};
use serde::Deserialize;

#[derive(Debug, Parser)]
#[command(
    name = "weevil",
    about = "Command-line toolkit for scraping NFO metadata",
    arg_required_else_help = true,
    after_help = "Option resolution (high -> low):\n  1) CLI flags\n  2) mode section in config ([name]/[file]/[dir]/[watch])\n  3) shared section in config ([shared])\n\nConfig file loading:\n  --config <FILE>\n  or ./weevil.toml when present."
)]
pub(crate) struct Cli {
    #[arg(
        long,
        short = 'c',
        value_name = "FILE",
        global = true,
        help = "Path to TOML config file; defaults to ./weevil.toml when present."
    )]
    pub(crate) config: Option<PathBuf>,
    #[arg(
        long,
        value_name = "FILE",
        global = true,
        help = "CSV file path for node-value mapping (node,to,from...; from supports extra columns)."
    )]
    pub(crate) node_mapping_csv: Option<PathBuf>,
    #[command(subcommand)]
    pub(crate) command: Command,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Deserialize)]
#[clap(rename_all = "kebab-case")]
#[serde(rename_all = "kebab-case")]
pub(crate) enum FolderMultiStrategy {
    HardLink,
    SoftLink,
    First,
}

#[derive(Debug, Subcommand)]
pub(crate) enum Command {
    #[command(
        name = "name",
        about = "Generate NFO output by name.",
        after_help = "Required effective fields:\n  script, output\n\nField priority (high -> low):\n  --script/--output > [name] > [shared]\n\nLua run() must return either:\n  - a table matching the NFO movie schema\n  - a raw NFO XML string"
    )]
    Name {
        #[arg(long, short = 'n', value_name = "NAME")]
        name: String,
        #[arg(
            long = "script",
            short = 's',
            value_name = "SCRIPT",
            num_args = 1..,
            action = clap::ArgAction::Append
        )]
        scripts: Vec<PathBuf>,
        #[arg(long, short = 'o', value_name = "OUTPUT")]
        output: Option<PathBuf>,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Enable multi-source aggregation across successful scripts."
        )]
        multi_source: bool,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Save remote poster/fanart images to local files."
        )]
        save_images: bool,
        #[arg(
            long,
            value_name = "COUNT",
            help = "Stop after collecting this many successful sources when multi-source is enabled; 0 means no limit."
        )]
        multi_source_max_sources: Option<u32>,
    },
    #[command(
        name = "file",
        about = "Generate NFO output from a file, then rename and move assets.",
        after_help = "Required effective fields:\n  script, output\n\nField priority (high -> low):\n  --script/--output/--input-name-rule/--folder-multi\n  > [file]\n  > [shared]"
    )]
    File {
        #[arg(
            long,
            short = 'i',
            value_name = "FILE",
            num_args = 1..,
            action = clap::ArgAction::Append,
            help = "Input file path; can be repeated. Split-part files in the same directory can be migrated with unified naming."
        )]
        input: Vec<PathBuf>,
        #[arg(
            long = "script",
            short = 's',
            value_name = "SCRIPT",
            num_args = 1..,
            action = clap::ArgAction::Append
        )]
        scripts: Vec<PathBuf>,
        #[arg(
            long,
            short = 'o',
            value_name = "OUTPUT",
            help = "Output path template (without extension)."
        )]
        output: Option<String>,
        #[arg(
            long = "input-name-rule",
            value_name = "RULE",
            help = "Input-name cleanup rule; can be repeated. Supports legacy tokens (including comma-separated list) and prefixed rules: literal:<text>, regex:<pattern>, replace:<from>=><to>, regex-replace:<pattern>=><to>."
        )]
        input_name_rules: Vec<String>,
        #[arg(
            long,
            value_enum,
            value_name = "MODE",
            help = "How to handle multiple output paths generated by the template."
        )]
        folder_multi: Option<FolderMultiStrategy>,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Enable multi-source aggregation across successful scripts."
        )]
        multi_source: bool,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Save remote poster/fanart images to local files."
        )]
        save_images: bool,
        #[arg(
            long,
            value_name = "COUNT",
            help = "Stop after collecting this many successful sources when multi-source is enabled; 0 means no limit."
        )]
        multi_source_max_sources: Option<u32>,
    },
    #[command(
        name = "dir",
        about = "Generate NFO output for each video file in a directory.",
        after_help = "Required effective fields:\n  input, script, output\n\nField priority (high -> low):\n  --input/--script/--output/--input-name-rule/--folder-multi/--max-depth/--fetch-threads/--throttle-same-script/--script-throttle-base-ms\n  > [dir]\n  > [shared]"
    )]
    Dir {
        #[arg(long, short = 'i', value_name = "DIR")]
        input: Option<PathBuf>,
        #[arg(
            long = "script",
            short = 's',
            value_name = "SCRIPT",
            num_args = 1..,
            action = clap::ArgAction::Append
        )]
        scripts: Vec<PathBuf>,
        #[arg(
            long,
            short = 'o',
            value_name = "OUTPUT",
            help = "Output path template (without extension)."
        )]
        output: Option<String>,
        #[arg(
            long = "input-name-rule",
            value_name = "RULE",
            help = "Input-name cleanup rule; can be repeated. Supports legacy tokens (including comma-separated list) and prefixed rules: literal:<text>, regex:<pattern>, replace:<from>=><to>, regex-replace:<pattern>=><to>."
        )]
        input_name_rules: Vec<String>,
        #[arg(
            long,
            value_enum,
            value_name = "MODE",
            help = "How to handle multiple output paths generated by the template."
        )]
        folder_multi: Option<FolderMultiStrategy>,
        #[arg(
            long,
            value_name = "DEPTH",
            allow_negative_numbers = true,
            help = "Maximum traversal depth; -1 means unlimited."
        )]
        max_depth: Option<i32>,
        #[arg(
            long,
            value_name = "COUNT",
            help = "Max concurrent tasks: 1=serial, >1=limited parallelism, 0=unlimited."
        )]
        fetch_threads: Option<u32>,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Whether to throttle same-script execution across different tasks."
        )]
        throttle_same_script: bool,
        #[arg(
            long,
            value_name = "MILLISECONDS",
            help = "Base delay in milliseconds for same-script throttle random wait."
        )]
        script_throttle_base_ms: Option<u64>,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Enable multi-source aggregation across successful scripts."
        )]
        multi_source: bool,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Save remote poster/fanart images to local files."
        )]
        save_images: bool,
        #[arg(
            long,
            value_name = "COUNT",
            help = "Stop after collecting this many successful sources when multi-source is enabled; 0 means no limit."
        )]
        multi_source_max_sources: Option<u32>,
    },
    #[command(
        name = "watch",
        about = "Watch a directory continuously and process newly completed video files.",
        after_help = "Required effective fields:\n  input, script, output\n\nField priority (high -> low):\n  --input/--script/--output/--input-name-rule/--folder-multi/--max-depth/--fetch-threads/--throttle-same-script/--script-throttle-base-ms\n  > [watch]\n  > [shared]"
    )]
    Watch {
        #[arg(long, short = 'i', value_name = "DIR")]
        input: Option<PathBuf>,
        #[arg(
            long = "script",
            short = 's',
            value_name = "SCRIPT",
            num_args = 1..,
            action = clap::ArgAction::Append
        )]
        scripts: Vec<PathBuf>,
        #[arg(
            long,
            short = 'o',
            value_name = "OUTPUT",
            help = "Output path template (without extension)."
        )]
        output: Option<String>,
        #[arg(
            long = "input-name-rule",
            value_name = "RULE",
            help = "Input-name cleanup rule; can be repeated. Supports legacy tokens (including comma-separated list) and prefixed rules: literal:<text>, regex:<pattern>, replace:<from>=><to>, regex-replace:<pattern>=><to>."
        )]
        input_name_rules: Vec<String>,
        #[arg(
            long,
            value_enum,
            value_name = "MODE",
            help = "How to handle multiple output paths generated by the template."
        )]
        folder_multi: Option<FolderMultiStrategy>,
        #[arg(
            long,
            value_name = "DEPTH",
            allow_negative_numbers = true,
            help = "Maximum traversal depth; -1 means unlimited."
        )]
        max_depth: Option<i32>,
        #[arg(
            long,
            value_name = "COUNT",
            help = "Max concurrent tasks: 1=serial, >1=limited parallelism, 0=unlimited."
        )]
        fetch_threads: Option<u32>,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Whether to throttle same-script execution across different tasks."
        )]
        throttle_same_script: bool,
        #[arg(
            long,
            value_name = "MILLISECONDS",
            help = "Base delay in milliseconds for same-script throttle random wait."
        )]
        script_throttle_base_ms: Option<u64>,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Enable multi-source aggregation across successful scripts."
        )]
        multi_source: bool,
        #[arg(
            long,
            action = clap::ArgAction::SetTrue,
            help = "Save remote poster/fanart images to local files."
        )]
        save_images: bool,
        #[arg(
            long,
            value_name = "COUNT",
            help = "Stop after collecting this many successful sources when multi-source is enabled; 0 means no limit."
        )]
        multi_source_max_sources: Option<u32>,
    },
    #[command(
        name = "scripts",
        about = "List Lua script metadata from CLI inputs or config defaults.",
        after_help = "Usage:
  weevil scripts --script a.lua --script b.lua
  weevil --config weevil.toml scripts

Resolution:
  If --script is provided, list those scripts.
  Otherwise, collect scripts from config defaults."
    )]
    Scripts {
        #[arg(
            long = "script",
            short = 's',
            value_name = "SCRIPT",
            num_args = 1..,
            action = clap::ArgAction::Append,
            help = "Lua script path; can be repeated."
        )]
        scripts: Vec<PathBuf>,
    },
}

#[cfg(test)]
#[path = "tests/cli.rs"]
mod tests;
